### ISSUE TITLE
Animations not working (THREE.PropertyBinding: No target node found for track) SOLVED

### ISSUE THREAD

**Issue by lakshaykhokhar2003** [adrianhajdin/threejs-portfolio#2]
I found the solution for the animations not working when you get the animation from Mixamo, but works perfectly fine with the animation provided by Adrian.

I console.log the animation that Adrian gave and the animation that I downloaded from Mixamo.

![image](https://github.com/user-attachments/assets/3eaf2e3c-7c5e-4df8-baf7-2b692e9e2ba0)
Above is the animation that Adrian provided.

![image](https://github.com/user-attachments/assets/bfdb3dd5-0c25-4796-b2ef-a729cfb1d0ea)
And the above is the animation that Mixamo gives us.

As you can see, the issue lies in the naming of files.

The Mixamo rewrites the name of the tracks with their own names in front of the original name (as a watermark, maybe idk).

You can add these lines of code in your Developer file, which will fix the issue.

    const {animations: yourAnimation} = useFBX('/models/animations/yourFile.fbx')
    const renameTracks = (animation: AnimationClip) => {
        animation.tracks.forEach((track) => {
            track.name = track.name.replace('mixamorig', '');
        });
    };
    renameTracks(yourAnimation[0]);

Use the above function to pass your animation with index 0.

NOTE: I am using TSX so just remove the type from the functions if you are using JSX

**Comment by DanielChen93** [comment]
Thanks for your input :)

**Comment by SunACong** [comment]
I encountered the same situation as you. However, when I added your code lines, it didn't render correctly. Maybe it's because when I converted the glb to fbx, since the official website of aspoase couldn't be used, I used other online tools.😭

**Comment by lakshaykhokhar2003** [comment]
Can you send console.log(animations) to see if it matches the starting characters "mixamorig"

**Comment by SunACong** [comment]
> Can you send console.log(animations) to see if it matches the starting characters "mixamorig"

Yes, it can be matched. I have checked that the replaced animations are successful. When I rendered the character's glb model independently, it was successful. However, the fbx animations couldn't be rendered. I used the console to check my animations and compared them with Adrian's. It seems that some properties of the object were affected during the conversion process. Anyway, thank you for your reply. If you have any good ideas, you can let me know. Thank you.

**Comment by atharv1030** [comment]
hey can u help me with the index.css file my css is not applying on the app.jsx file , please i am very tensed because of that problem

**Comment by lakshaykhokhar2003** [comment]
> hey can u help me with the index.css file my css is not applying on the app.jsx file , please i am very tensed because of that problem

Sure, send me your code. I’ll check it out and see if I can help
